"""initial_schema

Revision ID: a6bf9bbdd914
Revises: 
Create Date: 2026-06-08 01:06:37.459473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6bf9bbdd914'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('picture', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('connected_accounts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('token_expiry', sa.DateTime(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connected_accounts_email'), 'connected_accounts', ['email'], unique=False)
    op.create_table('email_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('gmail_message_id', sa.String(), nullable=False),
    sa.Column('gmail_thread_id', sa.String(), nullable=False),
    sa.Column('sender_email', sa.String(), nullable=False),
    sa.Column('sender_name', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('body_snippet', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('is_classified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['connected_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_records_gmail_message_id'), 'email_records', ['gmail_message_id'], unique=True)
    op.create_index(op.f('ix_email_records_gmail_thread_id'), 'email_records', ['gmail_thread_id'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email_record_id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('role_title', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('applied', 'screening', 'interview', 'offer', 'rejected', 'withdrawn', name='applicationstatus'), nullable=False),
    sa.Column('status_overridden', sa.Boolean(), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['connected_accounts.id'], ),
    sa.ForeignKeyConstraint(['email_record_id'], ['email_records.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_record_id')
    )
    op.create_index(op.f('ix_applications_company_name'), 'applications', ['company_name'], unique=False)
    op.create_table('email_feedback',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email_record_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('feedback', sa.Enum('confirm', 'reject', name='feedbacktype'), nullable=False),
    sa.Column('original_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['email_record_id'], ['email_records.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_feedback')
    op.drop_index(op.f('ix_applications_company_name'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_email_records_gmail_thread_id'), table_name='email_records')
    op.drop_index(op.f('ix_email_records_gmail_message_id'), table_name='email_records')
    op.drop_table('email_records')
    op.drop_index(op.f('ix_connected_accounts_email'), table_name='connected_accounts')
    op.drop_table('connected_accounts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
